# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 19:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=200)),
                ('blog_date', models.DateTimeField(verbose_name='date published')),
                ('blog_text', models.TextField(max_length=4000)),
            ],
        ),
    ]
